---
default_set: 'centos-64-x64'
sets:
  'centos-59-x64':
    nodes:
      'redis.puppet.vm':
        prefab: 'centos-59-x64'
  'centos-64-x64':
    nodes:
      'redis.puppet.vm':
        prefab: 'centos-64-x64'
  'fedora-18-x64':
    nodes:
      'redis.puppet.vm':
        prefab: 'fedora-18-x64'
  'ubuntu-server-10044-x64':
    nodes:
      'redis.puppet.vm':
        prefab: 'ubuntu-server-10044-x64'
  'ubuntu-server-12042-x64':
    nodes:
      'redis.puppet.vm':
        prefab: 'ubuntu-server-12042-x64'
