---
language: ruby
script: "bundle exec rake spec"
rvm:
  - 1.8.7
  - 1.9.3
notifications:
  hipchat:
    rooms:
      secure: "W+yc+gLrrz0TBWL7x9q1AiBRDBDlUtIF9QiqsNINEIGQARQE8R7J3UcZ30jT\n9zq2IpCyP37NMV70Cp9YsrIa41K+NxwPhnpT4WdY8k10X2iTYQVN1ogpJpMM\nB6/bsSZPhh+wRyckB5pZjWPZhLrOkIGPBbepWFTLXh4hsOxWKww="
